## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# value counts for the STATUS column
application_df['STATUS'].value_counts()

1    34294
0        5
Name: STATUS, dtype: int64

In [3]:
application_df['SPECIAL_CONSIDERATIONS'].value_counts()

N    34272
Y       27
Name: SPECIAL_CONSIDERATIONS, dtype: int64

Status and special considerations can be dropped since nearly all rows fall into one value

In [4]:
# Drop the non-beneficial ID columns, 'EIN', 'STATUS', 'SPECIAL_CONSIDERATIONS'
application_df = application_df.drop(['EIN', 'STATUS', 'SPECIAL_CONSIDERATIONS'], 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                19568
APPLICATION_TYPE       17
AFFILIATION             6
CLASSIFICATION         71
USE_CASE                5
ORGANIZATION            4
INCOME_AMT              9
ASK_AMT              8747
IS_SUCCESSFUL           2
dtype: int64

In [9]:
# Look at NAME value counts for binning
name_counts = application_df['NAME'].value_counts()
name_counts[name_counts > 5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [11]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name 'names_to_replace`
names_to_replace = list(name_counts[name_counts <= 5].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [12]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [13]:
# Choose a cutoff value (500) and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts < 500].index)


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [14]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [15]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [16]:
# Choose a cutoff value (1000) and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [17]:
# Generate categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_cat

['NAME',
 'APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT']

In [18]:
# Convert categorical data to numeric with `pd.get_dummies`
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df.head(3)

,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,NAME_ALPHA PHI OMEGA,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,108590,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,5000,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [19]:
# Split our preprocessed data into our features and target arrays
x = application_with_dummies_df.drop(['IS_SUCCESSFUL'], axis='columns').values
y = application_with_dummies_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [20]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)

## Compile, Train and Evaluate the Model

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# In order to optimize, add additional layer and additional nodes
number_input_features = len(x_train[0])
layer1Nodes = 100
layer2Nodes = 30
layer3Nodes = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer1Nodes, input_dim=number_input_features, activation='relu')
)

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer2Nodes, input_dim=layer1Nodes, activation='sigmoid')
)

# Third hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer3Nodes, input_dim=layer2Nodes, activation='sigmoid')
)

# Output layer
nn.add(
    tf.keras.layers.Dense(units=1, activation='sigmoid')
)

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               39600

 dense_1 (Dense)             (None, 30)                3030

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 42,951
Trainable params: 42,951
Non-trainable params: 0
_________________________________________________________________

In [22]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:
# Train the model
fit_model = nn.fit(x_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5003 - accuracy: 0.7685
Epoch 2/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4462 - accuracy: 0.7909
Epoch 3/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4372 - accuracy: 0.7953
Epoch 4/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4325 - accuracy: 0.7944
Epoch 5/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4296 - accuracy: 0.7952
Epoch 6/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4280 - accuracy: 0.7961
Epoch 7/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4255 - accuracy: 0.7978
Epoch 8/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4240 - accuracy: 0.7968
Epoch 9/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4232 - accuracy: 0.7973
Epoch 10/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4222 - accuracy: 0.7971
Epoch 11/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4216 - accuracy: 0.7976
Epoch 12/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4206 - accuracy: 0.7987
Epoch 13/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4195 - accuracy: 0.7982
Epoch 14/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4189 - accuracy: 0.7996
Epoch 15/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4183 - accuracy: 0.7994
Epoch 16/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4173 - accuracy: 0.7986
Epoch 17/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4168 - accuracy: 0.7990
Epoch 18/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4164 - accuracy: 0.8009
Epoch 19/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4160 - accuracy: 0.8010
Epoch 20/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4153 - accuracy: 0.8003
Epoch 21/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4148 - accuracy: 0.8017
Epoch 22/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4142 - accuracy: 0.8010
Epoch 23/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4135 - accuracy: 0.8014
Epoch 24/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4137 - accuracy: 0.8018
Epoch 25/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4129 - accuracy: 0.8007
Epoch 26/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4125 - accuracy: 0.8024
Epoch 27/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4127 - accuracy: 0.8013
Epoch 28/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4121 - accuracy: 0.8012
Epoch 29/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4115 - accuracy: 0.8032
Epoch 30/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4116 - accuracy: 0.8026
Epoch 31/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4111 - accuracy: 0.8023
Epoch 32/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4108 - accuracy: 0.8028
Epoch 33/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4109 - accuracy: 0.8026
Epoch 34/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4103 - accuracy: 0.8029
Epoch 35/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4107 - accuracy: 0.8029
Epoch 36/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4099 - accuracy: 0.8033
Epoch 37/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4098 - accuracy: 0.8035
Epoch 38/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4097 - accuracy: 0.8035
Epoch 39/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4098 - accuracy: 0.8029
Epoch 40/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4093 - accuracy: 0.8033
Epoch 41/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4090 - accuracy: 0.8045
Epoch 42/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4091 - accuracy: 0.8034
Epoch 43/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4093 - accuracy: 0.8038
Epoch 44/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4088 - accuracy: 0.8032
Epoch 45/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4083 - accuracy: 0.8029
Epoch 46/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4081 - accuracy: 0.8036
Epoch 47/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4081 - accuracy: 0.8033
Epoch 48/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4081 - accuracy: 0.8043
Epoch 49/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4076 - accuracy: 0.8035
Epoch 50/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4075 - accuracy: 0.8039
Epoch 51/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4073 - accuracy: 0.8035
Epoch 52/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4076 - accuracy: 0.8052
Epoch 53/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4067 - accuracy: 0.8047
Epoch 54/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4069 - accuracy: 0.8047
Epoch 55/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4072 - accuracy: 0.8045
Epoch 56/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4065 - accuracy: 0.8050
Epoch 57/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4067 - accuracy: 0.8046
Epoch 58/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4065 - accuracy: 0.8044
Epoch 59/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4063 - accuracy: 0.8046
Epoch 60/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4062 - accuracy: 0.8040
Epoch 61/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4066 - accuracy: 0.8045
Epoch 62/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8047
Epoch 63/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4057 - accuracy: 0.8052
Epoch 64/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8048
Epoch 65/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4055 - accuracy: 0.8052
Epoch 66/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4053 - accuracy: 0.8040
Epoch 67/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4051 - accuracy: 0.8042
Epoch 68/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4050 - accuracy: 0.8047
Epoch 69/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4050 - accuracy: 0.8049
Epoch 70/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4049 - accuracy: 0.8042
Epoch 71/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4050 - accuracy: 0.8046
Epoch 72/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4047 - accuracy: 0.8052
Epoch 73/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4050 - accuracy: 0.8046
Epoch 74/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8052
Epoch 75/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4049 - accuracy: 0.8053
Epoch 76/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4047 - accuracy: 0.8044
Epoch 77/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8052
Epoch 78/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8052
Epoch 79/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8048
Epoch 80/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4048 - accuracy: 0.8050
Epoch 81/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8055
Epoch 82/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4046 - accuracy: 0.8048
Epoch 83/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8049
Epoch 84/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8052
Epoch 85/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8046
Epoch 86/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4045 - accuracy: 0.8055
Epoch 87/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4049 - accuracy: 0.8052
Epoch 88/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4045 - accuracy: 0.8055
Epoch 89/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4046 - accuracy: 0.8054
Epoch 90/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8052
Epoch 91/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8054
Epoch 92/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4046 - accuracy: 0.8054
Epoch 93/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8047
Epoch 94/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8056
Epoch 95/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4045 - accuracy: 0.8060
Epoch 96/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8047
Epoch 97/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8055
Epoch 98/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8055
Epoch 99/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8058
Epoch 100/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8056
Epoch 101/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4037 - accuracy: 0.8060
Epoch 102/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8053
Epoch 103/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8059
Epoch 104/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8052
Epoch 105/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4038 - accuracy: 0.8050
Epoch 106/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8051
Epoch 107/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8050
Epoch 108/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4037 - accuracy: 0.8052
Epoch 109/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8060
Epoch 110/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4038 - accuracy: 0.8054
Epoch 111/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8059
Epoch 112/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8056
Epoch 113/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8066
Epoch 114/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8061
Epoch 115/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4034 - accuracy: 0.8055
Epoch 116/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4037 - accuracy: 0.8057
Epoch 117/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8059
Epoch 118/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4044 - accuracy: 0.8068
Epoch 119/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8067
Epoch 120/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8054
Epoch 121/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8063
Epoch 122/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4039 - accuracy: 0.8056
Epoch 123/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4044 - accuracy: 0.8068
Epoch 124/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4045 - accuracy: 0.8065
Epoch 125/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4045 - accuracy: 0.8063
Epoch 126/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8066
Epoch 127/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8063
Epoch 128/200
804/804 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8071
Epoch 129/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8063
Epoch 130/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8069
Epoch 131/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8066
Epoch 132/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8067
Epoch 133/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4038 - accuracy: 0.8062
Epoch 134/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8066
Epoch 135/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8059
Epoch 136/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8068
Epoch 137/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8068
Epoch 138/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4038 - accuracy: 0.8060
Epoch 139/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8064
Epoch 140/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8066
Epoch 141/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8065
Epoch 142/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4041 - accuracy: 0.8063
Epoch 143/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8063
Epoch 144/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8063
Epoch 145/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8062
Epoch 146/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8071
Epoch 147/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8068
Epoch 148/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8068
Epoch 149/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8071
Epoch 150/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8059
Epoch 151/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8066
Epoch 152/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8072
Epoch 153/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8078
Epoch 154/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8064
Epoch 155/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8065
Epoch 156/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4023 - accuracy: 0.8056
Epoch 157/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4027 - accuracy: 0.8066
Epoch 158/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8066
Epoch 159/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4027 - accuracy: 0.8068
Epoch 160/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8064
Epoch 161/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8064
Epoch 162/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8067
Epoch 163/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8071
Epoch 164/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8078
Epoch 165/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8068
Epoch 166/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8070
Epoch 167/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8068
Epoch 168/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8073
Epoch 169/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8067
Epoch 170/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8071
Epoch 171/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8071
Epoch 172/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4034 - accuracy: 0.8064
Epoch 173/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8073
Epoch 174/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8071
Epoch 175/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4034 - accuracy: 0.8069
Epoch 176/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4033 - accuracy: 0.8072
Epoch 177/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8066
Epoch 178/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4027 - accuracy: 0.8073
Epoch 179/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8071
Epoch 180/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8066
Epoch 181/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8071
Epoch 182/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8068
Epoch 183/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8067
Epoch 184/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4034 - accuracy: 0.8061
Epoch 185/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8070
Epoch 186/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8070
Epoch 187/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8074
Epoch 188/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8071
Epoch 189/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4029 - accuracy: 0.8068
Epoch 190/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4028 - accuracy: 0.8071
Epoch 191/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4031 - accuracy: 0.8071
Epoch 192/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8071
Epoch 193/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4034 - accuracy: 0.8074
Epoch 194/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8071
Epoch 195/200
804/804 [==============================] - 2s 2ms/step - loss: 0.4030 - accuracy: 0.8068
Epoch 196/200

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4516 - accuracy: 0.7955 - 447ms/epoch - 2ms/step
Loss: 0.45159685611724854, Accuracy: 0.7954518795013428

In [25]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')

**Report on Neural Net:**

The purpose of this analysis was to create a neural net to predict the liklihood of successful funding by Alphabet Soup, using a large historical dataset of previous applications, bot successful and unsuccessful.

The target in this model is whether or not funding was received, a binary yes/no condition. The features were the following: 
 'NAME',
 'APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT'

We removed the EID which was not relevant, as well as the 'special considerations' and 'status' as almost the entire data set had the same values in those columns.

We used a 3 layer neural net with neurons the length of the training data set, the addition of a third layer contributed to greater accuracy in the optimization process. We did achieve target performance with accuracy of 79%.

Optimization involved including the name as a part of the model, as many charities applied multiple times, and previous success in obtaining funding should lead to more success in later applications, meaning that name was a relevant feature to be included having been excluded in the original nueral net.